import { DomainMeta } from "@/types/form";

export const techDomains: Record<string, DomainMeta> = {
  "web-development": {
    label: "Web Development",
    icon: "🌐",
    color: "from-blue-500 to-cyan-400",
    description: "Frontend, backend, and full-stack web apps",
    questions: [
      {
        id: "wd-1",
        question: "How familiar are you with building websites?",
        type: "mcq",
        options: ["Complete beginner", "I know basic HTML/CSS", "I understand some JavaScript", "I have built a basic website", "I have intermediate experience"],
      },
      {
        id: "wd-2",
        question: "Have you ever used a code editor like VS Code?",
        type: "mcq",
        options: ["No, never", "I've installed one but rarely use it", "Yes, I use it for practicing", "Yes, I use it frequently"],
      },
      {
        id: "wd-3",
        question: "What part of a website interests you the most?",
        type: "mcq",
        options: ["The visual design (Frontend)", "The database and logic (Backend)", "Both equally (Full-stack)", "Not sure yet"],
      },
      {
        id: "wd-4",
        question: "Have you ever tried following a web development tutorial?",
        type: "mcq",
        options: ["No, not yet", "Yes, but I didn't finish it", "Yes, I built a small project from a tutorial", "Yes, I build projects without tutorials now"],
      },
      {
        id: "wd-5",
        question: "What kind of web project would you love to build?",
        type: "mcq",
        options: ["E-commerce / Store", "Social Media App", "Portfolio / Blog", "SaaS / Tool", "Other/Undecided"],
      },
    ],
    youtubeKeywords: ["web development day in life", "junior developer routine", "web dev motivation"],
  },
  "data-science": {
    label: "Data Science",
    icon: "📊",
    color: "from-green-500 to-emerald-400",
    description: "Analytics, visualization, and insights from data",
    questions: [
      {
        id: "ds-1",
        question: "How comfortable are you with working with numbers and data?",
        type: "mcq",
        options: ["Not very comfortable", "Comfortable with basic math", "Enjoy analyzing statistics", "Very comfortable with complex data"],
      },
      {
        id: "ds-2",
        question: "Have you ever used spreadsheet software like Microsoft Excel or Google Sheets?",
        type: "mcq",
        options: ["Never used them", "Know basic formulas", "Can make robust charts/graphs", "Can write complex macros/scripts", "Expert user"],
      },
      {
        id: "ds-3",
        question: "What is your comfort level with Python for data analysis?",
        type: "mcq",
        options: ["Never used Python", "Know basic syntax", "Written simple scripts", "Familiar with basic data libraries", "Comfortable with advanced data analysis"],
      },
      {
        id: "ds-4",
        question: "What aspect of data science sounds most appealing?",
        type: "mcq",
        options: ["Creating visual charts and graphs", "Predicting future trends", "Organizing messy data", "Finding hidden patterns", "Not sure yet"],
      },
      {
        id: "ds-5",
        question: "What kind of data problem excites you most?",
        type: "mcq",
        options: ["Predictive Modeling", "Data Visualization", "Natural Language Processing", "Computer Vision", "Other/Undecided"],
      },
    ],
    youtubeKeywords: ["data scientist day in life", "data science student routine", "data analyst motivation"],
  },
  "machine-learning": {
    label: "Machine Learning & AI",
    icon: "🤖",
    color: "from-purple-500 to-violet-400",
    description: "AI models, neural networks, and intelligent systems",
    questions: [
      {
        id: "ml-1",
        question: "What do you know about Artificial Intelligence so far?",
        type: "mcq",
        options: ["I only know it from movies/ChatGPT", "I understand basic concepts like training", "I know some AI terminology", "I have implemented basic models"],
      },
      {
        id: "ml-2",
        question: "How comfortable are you with programming in general?",
        type: "mcq",
        options: ["Absolute beginner", "I know basic Python/C++", "I can write small programs", "I am very comfortable coding"],
      },
      {
        id: "ml-3",
        question: "Are you comfortable with basic algebra and probability?",
        type: "mcq",
        options: ["Not at all", "I remember some high school math", "I am fairly comfortable", "I excel at math algorithms"],
      },
      {
        id: "ml-4",
        question: "What is your main motivation for learning ML?",
        type: "mcq",
        options: ["Curiosity about how AI works", "Building cool AI applications", "Research and academic interest", "Career opportunities"],
      },
      {
        id: "ml-5",
        question: "What AI application do you most want to build?",
        type: "mcq",
        options: ["Chatbot / LLM", "Image / Video Generation", "Recommendation System", "Autonomous Agents", "Other/Undecided"],
      },
    ],
    youtubeKeywords: ["machine learning engineer day in life", "AI researcher routine", "deep learning student motivation"],
  },
  "cybersecurity": {
    label: "Cybersecurity",
    icon: "🔐",
    color: "from-red-500 to-orange-400",
    description: "Ethical hacking, network security, and defense",
    questions: [
      {
        id: "cs-1",
        question: "What is your current knowledge in cybersecurity?",
        type: "mcq",
        options: ["Curious absolute beginner", "Know basic computer concepts", "Know basic networking concepts", "Practiced basic CTF challenges"],
      },
      {
        id: "cs-2",
        question: "Have you ever used a command-line interface (CLI) or terminal?",
        type: "mcq",
        options: ["Never", "I know a few basic commands", "I can navigate directories easily", "I use it frequently"],
      },
      {
        id: "cs-3",
        question: "What operating systems are you familiar with?",
        type: "mcq",
        options: ["Windows only", "Mac only", "Windows and Mac", "Familiar with Linux as well"],
      },
      {
        id: "cs-4",
        question: "Which aspect of security sounds more interesting?",
        type: "mcq",
        options: ["Ethical Hacking (Attacking)", "Defending Networks (Protecting)", "Investigating Hacks (Forensics)", "Not sure yet"],
      },
      {
        id: "cs-5",
        question: "Which of these concepts do you want to learn more about?",
        type: "mcq",
        options: ["Penetration Testing", "Security Auditing", "Cryptography", "Malware Analysis", "Other/Undecided"],
      },
    ],
    youtubeKeywords: ["cybersecurity analyst day in life", "ethical hacker routine", "security engineer motivation"],
  },
  "mobile-development": {
    label: "Mobile Development",
    icon: "📱",
    color: "from-pink-500 to-rose-400",
    description: "iOS, Android, and cross-platform apps",
    questions: [
      {
        id: "mob-1",
        question: "What is your mobile development experience?",
        type: "mcq",
        options: ["Total beginner", "I have tried some beginner tutorials", "Built 1-2 small apps", "Published an app"],
      },
      {
        id: "mob-2",
        question: "Have you ever written code before in any language?",
        type: "mcq",
        options: ["No, never", "A little bit in school/college", "Yes, I know basic programming concepts", "Yes, I am comfortable coding"],
      },
      {
        id: "mob-3",
        question: "What type of phone uses you most?",
        type: "mcq",
        options: ["Android phone", "iPhone", "I use both", "None of the above"],
      },
      {
        id: "mob-4",
        question: "Which platform are you most interested in developing for first?",
        type: "mcq",
        options: ["Android only", "iOS (iPhone) only", "Both Android and iOS simultaneously", "Not sure yet"],
      },
      {
        id: "mob-5",
        question: "What app idea have you been thinking about?",
        type: "mcq",
        options: ["Utility / Productivity App", "Social / Communication", "E-commerce App", "Gaming / Entertainment", "Other/Undecided"],
      },
    ],
    youtubeKeywords: ["mobile developer day in life", "iOS developer routine", "Flutter developer motivation"],
  },
  "cloud-computing": {
    label: "Cloud Computing",
    icon: "☁️",
    color: "from-sky-500 to-blue-400",
    description: "AWS, GCP, Azure, and infrastructure at scale",
    questions: [
      {
        id: "cc-1",
        question: "How much do you know about how the internet works?",
        type: "mcq",
        options: ["Very little", "I know what servers and URLs are", "I understand IPs and domains", "I know how web hosting works securely"],
      },
      {
        id: "cc-2",
        question: "Have you ever rented a server or deployed a website online?",
        type: "mcq",
        options: ["Never", "Used free basic hosting", "Rented a simple VPS", "Used AWS/GCP/Azure before"],
      },
      {
        id: "cc-3",
        question: "What interests you most about cloud computing?",
        type: "mcq",
        options: ["Storing vast amounts of data", "Hosting websites that never crash", "Saving money for businesses", "Not sure yet"],
      },
      {
        id: "cc-4",
        question: "Are you comfortable with the Command Line Interface (CLI)?",
        type: "mcq",
        options: ["Not at all", "I know a few commands", "I can use it comfortably", "I prefer CLI over GUI apps"],
      },
      {
        id: "cc-5",
        question: "What kind of cloud project would you like to build?",
        type: "mcq",
        options: ["Scalable Web Backend", "Serverless Architecture", "Data Pipeline", "Microservices", "Other/Undecided"],
      },
    ],
    youtubeKeywords: ["cloud engineer day in life", "DevOps engineer routine", "AWS certification motivation"],
  },
  "game-development": {
    label: "Game Development",
    icon: "🎮",
    color: "from-yellow-500 to-amber-400",
    description: "2D/3D games, game engines, and interactive experiences",
    questions: [
      {
        id: "gd-1",
        question: "Have you ever tried making a game before?",
        type: "mcq",
        options: ["No, just a gamer", "Tried basic drag-and-drop tools like Scratch", "Followed some basic Unity/Godot tutorials", "Made a small test game"],
      },
      {
        id: "gd-2",
        question: "Are you more interested in the logic or the art?",
        type: "mcq",
        options: ["Game programming and logic", "Game art and animation", "Level design and writing", "A bit of everything"],
      },
      {
        id: "gd-3",
        question: "What type of games do you enjoy playing the most?",
        type: "mcq",
        options: ["2D Platformers/RPGs", "3D Shooters/Action", "Strategy/Puzzle", "Multiplayer Competitive"],
      },
      {
        id: "gd-4",
        question: "Have you used any game engine software before?",
        type: "mcq",
        options: ["Never used any", "Opened one but it was too complex", "Used GameMaker or similar 2D engine", "Familiar with Unity/Unreal Engine"],
      },
      {
        id: "gd-5",
        question: "What type of game do you want to create?",
        type: "mcq",
        options: ["2D Platformer / RPG", "3D Shooter / Action", "Puzzle / Casual Game", "Multiplayer / Co-op", "Other/Undecided"],
      },
    ],
    youtubeKeywords: ["indie game developer day in life", "game dev routine", "Unity developer motivation"],
  },
  "ui-ux-design": {
    label: "UI/UX Design",
    icon: "🎨",
    color: "from-fuchsia-500 to-purple-400",
    description: "User interfaces, design systems, and user research",
    questions: [
      {
        id: "ux-1",
        question: "How familiar are you with design concepts?",
        type: "mcq",
        options: ["Complete beginner", "I have an eye for good design", "I know basic color and layout principles", "I study professional interfaces"],
      },
      {
        id: "ux-2",
        question: "Have you ever used software like Canva, Figma, or Photoshop?",
        type: "mcq",
        options: ["No, never", "Used Canva for basic school projects", "Tried Figma or Sketch slightly", "I am familiar with design tools"],
      },
      {
        id: "ux-3",
        question: "What excites you more in UX/UI?",
        type: "mcq",
        options: ["Making things look incredibly beautiful (UI)", "Making things easy and logical to use (UX)", "Both equally", "Not sure yet"],
      },
      {
        id: "ux-4",
        question: "Have you ever drawn wireframes or sketches for an app idea?",
        type: "mcq",
        options: ["Never thought about it", "Yes, just rough sketches on paper", "Yes, structured mockups on paper", "Yes, using software"],
      },
      {
        id: "ux-5",
        question: "What kind of product would you like to design?",
        type: "mcq",
        options: ["Minimalist Web App", "Complex Dashboard", "Mobile Application", "E-commerce Platform", "Other/Undecided"],
      },
    ],
    youtubeKeywords: ["UX designer day in life", "product designer routine", "Figma UI design motivation"],
  },
  "devops": {
    label: "DevOps & Automation",
    icon: "⚙️",
    color: "from-slate-500 to-gray-400",
    description: "CI/CD, containers, infrastructure automation",
    questions: [
      {
        id: "do-1",
        question: "What is your understanding of DevOps?",
        type: "mcq",
        options: ["Never heard of it", "I know it relates to servers and automation", "I know about CI/CD pipelines basics", "I have studied tools like Docker"],
      },
      {
        id: "do-2",
        question: "Are you comfortable working in a command-line/terminal environment?",
        type: "mcq",
        options: ["Not at all", "I know some basic commands", "I can navigate and edit files", "I am very comfortable"],
      },
      {
        id: "do-3",
        question: "Do you have any programming or scripting experience?",
        type: "mcq",
        options: ["No programming experience", "Know some basic coding", "Can write simple Bash/Python scripts", "Can write advanced automation scripts"],
      },
      {
        id: "do-4",
        question: "What sounds most interesting to you?",
        type: "mcq",
        options: ["Automating repetitive tasks", "Managing large computer server farms", "Monitoring app performance securely", "Not sure yet"],
      },
      {
        id: "do-5",
        question: "What automation problem would you like to solve?",
        type: "mcq",
        options: ["Automated Deployment Pipeline", "Infrastructure as Code", "Monitoring & Alerts Setup", "Container Orchestration", "Other/Undecided"],
      },
    ],
    youtubeKeywords: ["DevOps engineer day in life", "SRE routine", "Kubernetes automation motivation"],
  },
  "blockchain": {
    label: "Blockchain & Web3",
    icon: "⛓️",
    color: "from-orange-500 to-yellow-400",
    description: "Smart contracts, DeFi, and decentralized apps",
    questions: [
      {
        id: "bc-1",
        question: "What is your understanding of Blockchain currently?",
        type: "mcq",
        options: ["I just know Crypto/Bitcoin names", "I know the basic concept of decentralized ledgers", "I have studied how smart contracts work", "I have written basic blockchain code"],
      },
      {
        id: "bc-2",
        question: "Have you ever bought or transferred cryptocurrency?",
        type: "mcq",
        options: ["No, never interacted with it", "Yes, just on central exchanges", "Yes, using personal wallets (like MetaMask)"],
      },
      {
        id: "bc-3",
        question: "Do you have past coding experience in general?",
        type: "mcq",
        options: ["No coding experience", "Some basic HTML/Python", "Understanding of Java/C++ basics", "Proficient in languages like JavaScript"],
      },
      {
        id: "bc-4",
        question: "Which aspect of Web3 excites you most?",
        type: "mcq",
        options: ["Decentralized Finance (DeFi)", "Digital Assets (NFTs)", "Decentralized Applications (dApps)", "Cryptographic Security Principles"],
      },
      {
        id: "bc-5",
        question: "What Web3 project idea excites you?",
        type: "mcq",
        options: ["Decentralized Exchange (DEX)", "NFT Marketplace", "DAO Tooling", "Tokenomics System", "Other/Undecided"],
      },
    ],
    youtubeKeywords: ["blockchain developer day in life", "Web3 developer routine", "Solidity developer motivation"],
  },
};
